//
//  TopGamesPresenterTests.swift
//  TwitchTopGames
//
//  Created by mazza on 20/09/19.
//  Copyright (c) 2019 fbassi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TwitchTopGames
import XCTest

class TopGamesPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: TopGamesPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupTopGamesPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupTopGamesPresenter() {
        sut = TopGamesPresenter()
    }
    
    // MARK: Test doubles
    
    class TopGamesDisplayLogicSpy: TopGamesDisplayLogic {
        var displayTopGamesCalled = false
        
        func displayTopGames(viewModel: TopGames.Get.ViewModel?) {
            displayTopGamesCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentTopGamesReceiveResponseNilValues() {
        // Given
        let spy = TopGamesDisplayLogicSpy()
        sut.viewController = spy
        let response = TopGames.Get.Response(total: nil, top: nil)
        
        // When
        sut.presentTopGames(response: response)
        
        // Then
        XCTAssertTrue(spy.displayTopGamesCalled, "presentTopGames(response:) should ask the view controller to display the result")
    }
}
