//
//  TopGamesWorkerTests.swift
//  TwitchTopGames
//
//  Created by mazza on 20/09/19.
//  Copyright (c) 2019 fbassi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TwitchTopGames
import XCTest

class TopGamesWorkerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: TopGamesWorker!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupTopGamesWorker()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupTopGamesWorker() {
        sut = TopGamesWorker()
    }
    
    // MARK: Test doubles
    
    class MockTopGamesWorker: TopGamesWorker {
        
        var fetchTopGamesCalled = false
        var request: TopGames.Get.Request?
        
        override func fetchTopGames(request: TopGames.Get.Request, completionHandler: @escaping (Result<TopGames.Get.Response, APIError>) -> Void) {
            fetchTopGamesCalled = true
            self.request = request
            let response = TopGames.Get.Response(total: nil, top: nil)
            completionHandler(Result.success(response))
        }
    }
    
    // MARK: Tests
    
    func testCompletionHandler() {
        //When
        let expect = expectation(description: "It should call the completion handler")
        let worker = MockTopGamesWorker()
        //Given
        let request = TopGames.Get.Request(service: .getTopGames(limit: 25, offset: 0))
        
        worker.fetchTopGames(request: request, completionHandler: { (result) in
            //Then
            expect.fulfill()
        })
        
        waitForExpectations(timeout: 0.1) { (error) in
            print("Timeout error: \(String(describing: error))")
        }
    }
}
