//
//  TopGamesPresenter.swift
//  TwitchTopGames
//
//  Created by mazza on 04/09/19.
//  Copyright (c) 2019 fbassi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopGamesPresentationLogic {
    
}

class TopGamesPresenter: TopGamesPresentationLogic {
    weak var viewController: TopGamesDisplayLogic?
}
