//
//  TopGamesViewController.swift
//  TwitchTopGames
//
//  Created by mazza on 04/09/19.
//  Copyright (c) 2019 fbassi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: TopGameCell

class TopGameCell: BaseTableViewCell<TopGames.Get.ViewModel.DisplayedGame> {
    override var item: TopGames.Get.ViewModel.DisplayedGame? {
        didSet {
            if let item = item {
                self.stackViewCell.isHidden = false
                self.activityLoadingCell.stopAnimating()
                self.imageViewGame.loadImageUsingCacheWithURL(item.gameImageUrl, placeHolder: UIImage(named: "topGameImageMock")) { (completion) in

                }
                self.labelGameName.text = item.localizedName
                self.labelGamePopularityValue.text = "\(item.popularity.formattedWithSeparator)"
                
                //TODO: verify inside core data before showing button type and image
                self.buttonFavorite.isEnabled = false
                
                //TODO: get top 5 clips for this gamecell and show inside a collection
            }else {
                self.stackViewCell.isHidden = true
                self.activityLoadingCell.startAnimating()
            }
        }
    }
    
    // MARK: IBOutlets
    
    @IBOutlet weak var activityLoadingCell: UIActivityIndicatorView!
    @IBOutlet weak var stackViewCell: UIStackView!
    @IBOutlet weak var imageViewGame: UIImageView!
    @IBOutlet weak var labelGameName: UILabel!
    @IBOutlet weak var labelGamePopularityValue: UILabel!
    @IBOutlet weak var buttonFavorite: UIButton!
    
    @IBOutlet weak var collectionTopClips: UICollectionView!
    
    // MARK: IBActions
    @IBAction func buttonFavoriteTapped(_ sender: UIButton) {
        //TODO: verify inside core data before adding / remove item
    }
}

protocol TopGamesDisplayLogic: class {
    func displayTopGames(viewModel: TopGames.Get.ViewModel?)
}

class TopGamesViewController: UIViewController, TopGamesDisplayLogic {
    var interactor: TopGamesBusinessLogic?
    var router: (NSObjectProtocol & TopGamesRoutingLogic & TopGamesDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = TopGamesInteractor()
        let presenter = TopGamesPresenter()
        let router = TopGamesRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
  
    // MARK: IBOutlets
    @IBOutlet weak var tableView: UITableView!
    
    // MARK: IBActions
    
    @objc func refresh(_ sender: Any) {
        self.currentPage = 0
        self.genericDataSource = nil
        self.getTopGames()
    }
    
    // MARK:- UI
    private let searchController = UISearchController(searchResultsController: nil)
    
    // MARK: Proprieties
    private var genericDataSource: GenericTableViewDataSource<TopGameCell, TopGames.Get.ViewModel.DisplayedGame>?
    private let gamesLimit: Int = 25
    private var currentPage: Int = 0
    private var totalPages: Int?
    private var isFetchInProgress = false
    
    fileprivate let topGameCellIdentifier = K.ViewControllers.TopGames.Cells.topGameCellIdentifier
    fileprivate let topClipCollectionCellIdentifier = K.ViewControllers.TopGames.Cells.topClipCellIdentifier
    var refreshControl: UIRefreshControl!
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.setupNavigationBar()
        self.setupSearchBar()
        self.configPullToRefresh()
        self.getTopGames()
    }
    
    // MARK: Functions
    
    private func setupNavigationBar() {
        self.navigationController?.visibleViewController?.title = K.ViewControllers.TopGames.title
    }
    
    private func setupSearchBar() {
        self.navigationController?.visibleViewController?.navigationItem.hidesSearchBarWhenScrolling = true
        searchController.obscuresBackgroundDuringPresentation = false
        self.navigationController?.visibleViewController?.navigationItem.searchController = searchController
        searchController.searchBar.delegate = self
    }
    
    private func configPullToRefresh() {
        refreshControl = UIRefreshControl()
        refreshControl.addTarget(self, action: #selector(refresh), for: UIControl.Event.valueChanged)
        tableView.addSubview(refreshControl)
    }
    
    private func getTopGames() {
        DispatchQueue.global(qos: .background).async {
            guard !self.isFetchInProgress else {
                return
            }
            self.isFetchInProgress = true
            let request = TopGames.Get.Request(service: .getTopGames(limit: self.gamesLimit, offset: self.currentPage))
            self.interactor?.getTopGames(request: request)
        }
    }
    
    private func setupDataSource(with models: [TopGames.Get.ViewModel.DisplayedGame], andTotal total: Int? = nil) {
        if self.genericDataSource == nil {
            self.genericDataSource = GenericTableViewDataSource(models: models, identifier: self.topGameCellIdentifier, totalForInifityScroll: total) { cell, model in
                cell.item = model
                return cell
            }
            self.tableView?.dataSource = self.genericDataSource
            self.tableView?.prefetchDataSource = self.genericDataSource
            self.tableView?.reloadData()
            self.genericDataSource?.genericPrefetchingDelegate = self
        }else {
            self.genericDataSource?.updateModels(models)
        }
    }
    
    
    // MARK: TopGamesDisplayLogic
    
    func displayTopGames(viewModel: TopGames.Get.ViewModel?) {
        self.isFetchInProgress = false
        self.totalPages = viewModel?.totalPages
        self.refreshControl.endRefresh(completion: {
            if let viewModel = viewModel {
                self.currentPage += self.gamesLimit
                self.tableView.removePlaceholder(seperatorBackToDefault: true)
                self.setupDataSource(with: viewModel.displayedGames, andTotal: viewModel.totalPages)
            }else {
                if self.genericDataSource == nil {
                    self.tableView?.dataSource = nil
                    self.tableView.showPlaceholder()
                    self.showToast()
                }
            }
        })
    }
}

extension TopGamesViewController: GenericTableViewDataSourcePrefetchingDelegate {
    func fetchNewData() {
        self.getTopGames()
    }
}

extension TopGamesViewController: UISearchBarDelegate {
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        self.genericDataSource?.search(query: searchText)
        self.tableView.reloadData()
    }
}
