//
//  TopGamesPresenter.swift
//  TwitchTopGames
//
//  Created by mazza on 04/09/19.
//  Copyright (c) 2019 fbassi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopGamesPresentationLogic {
    func presentTopGames(response: TopGames.Get.Response?)
}

class TopGamesPresenter: TopGamesPresentationLogic {
    weak var viewController: TopGamesDisplayLogic?
    
    func presentTopGames(response: TopGames.Get.Response?) {
        
        guard let tops = response?.top else {
            self.presentError()
            return
        }
        var displayedGames = [TopGames.Get.ViewModel.DisplayedGame]()
        for top in tops {
            if let gameName = top.game?.name,
                let popularityValue = top.game?.popularity,
                let localizedName = top.game?.localizedName {
                if let url = URL(string: top.game?.box?.template?.replacingOccurrences(of: "{width}", with: "100").replacingOccurrences(of: "{height}", with: "100") ?? "https://static-cdn.jtvnw.net/ttv-static/404_boxart.jpg") {
                    let displayedGame = TopGames.Get.ViewModel.DisplayedGame(gameName: gameName, popularity: popularityValue, localizedName: localizedName, gameImageUrl: url)
                    displayedGames.append(displayedGame)
                }else {
                    self.presentError()
                    return
                }
            }else {
                self.presentError()
                return
            }
        }
        guard let total = response?.total else {
            self.presentError()
            return
        }
        let viewModel = TopGames.Get.ViewModel(totalPages: total, displayedGames: displayedGames)
        viewController?.displayTopGames(viewModel: viewModel)
    }
    
    private func presentError() {
        viewController?.displayTopGames(viewModel: nil)
    }
}
