//
//  TopGamesWorker.swift
//  TwitchTopGames
//
//  Created by mazza on 04/09/19.
//  Copyright (c) 2019 fbassi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TopGamesWorker: APIClient {
    let session: URLSession
    
    init(configuration: URLSessionConfiguration) {
        self.session = URLSession(configuration: configuration)
    }
    
    convenience init() {
        self.init(configuration: .default)
    }
    
    func fetchTopGames(request: TopGames.Get.Request, completionHandler: @escaping (Result<TopGames.Get.Response, APIError>) -> Void){
        let endpoint = request.service
        
        fetch(with: endpoint.request, httpMethod: .GET, decode: { json -> TopGames.Get.Response? in
            guard let feedResult = json as? TopGames.Get.Response else { return  nil }
            return feedResult
        }, completion: completionHandler)
    }
    
    func fetchTopClips(request: TopGames.Get.Request, completionHandler: @escaping (Result<TopGames.Get.Response, APIError>) -> Void){
        let endpoint = request.service
        
        fetch(with: endpoint.request, httpMethod: .GET, decode: { json -> TopGames.Get.Response? in
            guard let feedResult = json as? TopGames.Get.Response else { return  nil }
            return feedResult
        }, completion: completionHandler)
    }
}
