//
//  TopGamesModels.swift
//  TwitchTopGames
//
//  Created by mazza on 04/09/19.
//  Copyright (c) 2019 fbassi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TopGames {
    
    struct Get {
        
        struct Request {
            
        }
        
        // MARK: - Response
        struct Response: Codable {
            let total: Int?
            let top: [Top]?
            
            enum CodingKeys: String, CodingKey {
                case total = "_total"
                case top
            }
        }
        
        // MARK: - Top
        struct Top: Codable {
            let game: Game?
            let viewers, channels: Int?
        }
        
        // MARK: - Game
        struct Game: Codable {
            let name: String?
            let popularity, id, giantbombId: Int?
            let box, logo: Box?
            let localizedName: String?
            let locale: Locale?
            
            enum CodingKeys: String, CodingKey {
                case name, popularity
                case id = "_id"
                case giantbombId = "giantbomb_id"
                case box, logo
                case localizedName = "localized_name"
                case locale
            }
        }
        
        // MARK: - Box
        struct Box: Codable {
            let large, medium, small: String?
            let template: String?
        }
        
        enum Locale: String, Codable {
            case enUs = "en-us"
        }
    }
    
    struct ViewModel {
        
    }
}
