//
//  TopGamesInteractor.swift
//  TwitchTopGames
//
//  Created by mazza on 04/09/19.
//  Copyright (c) 2019 fbassi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopGamesBusinessLogic {
    func getTopGames(request: TopGames.Get.Request)
}

protocol TopGamesDataStore {
    
}

class TopGamesInteractor: TopGamesBusinessLogic, TopGamesDataStore {
    var presenter: TopGamesPresentationLogic?
    var worker = TopGamesWorker()
    
    func getTopGames(request: TopGames.Get.Request) {
        self.worker.fetchTopGames(request: request) { (result) in
            switch result {
            case .success(let topGames):
                self.presenter?.presentTopGames(response: topGames)
            case.failure:
                self.presenter?.presentTopGames(response: nil)
            }
        }
        
    }
}
